### ISSUE TITLE
Allow the use of default CXX flags

### ISSUE THREAD

**Issue by apoleon** [thelaui/M.A.R.S.#10]
Please find attached a patch that removes the fixed values for CXXFLAGS and allows the use of custom ones. You could also just add a variable such as ${CMAKE_CXX_FLAGS}.

https://gist.github.com/apoleon/ca260c104cc0a1fa401b

**Comment by eXpl0it3r** [comment]
I used the alternative that was provided with https://github.com/jwrdegoede/M.A.R.S./commit/4a88ceee9ba54774b462c1ae5e19411ba83dc5bf
