### ISSUE TITLE
Please create an AppData file

### ISSUE THREAD

**Issue by hughsie** [thelaui/M.A.R.S.#14]
Please consider writing and installing an AppData file with the application description and some screenshots, else M.A.R.S. looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by lightonflux** [comment]
Thanks for the notice.

I created the file, but it may need some work.

* I don't know if the email address still works.
* Simon needs to agree to the meta data license, because i took some snippets from [the about page](http://mars-game.sourceforge.net/?page_id=10).
* Someone needs to check it, i might made some mistakes.


        <?xml version="1.0" encoding="UTF-8"?>
        
        <component type="game">
         <id>mars.desktop</id>
         <metadata_license>CC0-1.0</metadata_license>
         <project_license>GPL-3.0+</project_license>
         <name>M.A.R.S.</name>
         <summary>M.A.R.S. is a game for two players, flying with ships in a two-dimensional space setting, governed by the laws of gravity.</summary>
         <description>
          <p>
           In year 3547, civilizations all over the galaxy have settled their own planets, living in peace and harmony with its environment. But outside the contemplative habitats, the GREAT WAR is raging. As a famous fighter on your way to never ending honor and prosperity, you have to protect your planet from the oncoming doom of your jealous neighbours!
          </p>
          <p>Features:</p>
          <ul>
           <li>awesome 2D-graphics with an unique style and shader support</li>
           <li>a stunning amount of particles</li>
           <li>single- and multiplayer-support (2 players local)</li>
           <li>artificial intelligence using an aggro-system, which reacts differently upon varying situations and uses inter-bot communication via jobs</li>
           <li>many impressive weapons and specials</li>
           <li>customizable ships</li>
           <li>a very sexy GUI</li>
           <li>support for many different languages</li>
          </ul>
          <p>Game types:</p>
          <ul>
           <li>SPACEBALL: Protect your planet from the sphere of death and defeat your enemies by letting it crush into their ridiculous globe.</li>
           <li>TEAMDEATHMATCH: Protect your comrades and destroy your enemies!
        Teach them a lesson, they will never forget.</li>
           <li>GRAVE-ITATION-PIT: Kill your enemies with a weapon that kills instantly but is really affine to gravitation.</li>
           <li>CANNONKEEP: A monolithic weapon of mass destruction is levitating over your galaxy. Reach its control first and turn your enemy’s home planet into a place of desolation!</li>
           <li>DEATHMATCH: Resist the other fighters and earn points by destroying the nutshells, they call ships.</li>
          </ul>
         </description>
         <screenshots>
          <screenshot type="default">
           <image>http://mars-game.sourceforge.net/wordpress/wp-content/uploads/gallery/revision_175/screenshot_111211104719.jpg</image>
           <caption>The games main menu.</caption>
          </screenshot>
          <screenshot>
           <image>http://mars-game.sourceforge.net/wordpress/wp-content/uploads/gallery/revision_175/screenshot_11121111229.jpg</image>
           <caption>A TDM game in action, with lots of explosions.</caption>
          </screenshot>
          <screenshot>
           <image>http://mars-game.sourceforge.net/wordpress/wp-content/uploads/gallery/revision_175/screenshot_111211105936.jpg</image>
           <caption>The statistics of a just finished game.</caption>
          </screenshot>
         </screenshots>
         <url type="homepage">http://mars-game.sourceforge.net</url>
         <updatecontact>marscoreteam@googlemail.com</updatecontact>
         <project_group>M.A.R.S. core developers</project_group>
        </component>

**Comment by hughsie** [comment]
Great, thanks. This actually failed validation tho:

$ appstream-util validate mars.appdata.xml 
mars.appdata.xml: FAILED:
• attribute-invalid     : <id> has invalid type attribute
• style-invalid         : <caption> cannot end in '.'
• style-invalid         : <summary> is too long
• style-invalid         : <li> requires sentence case
• style-invalid         : <li> is too long
• style-invalid         : <li> is too short
• style-invalid         : Not enough <p> content before <ul>
• style-invalid         : <li> cannot end in '.'
Validation of files failed

The most important bit is the type value in <i> -- that has to be desktop in your case.

**Comment by lightonflux** [comment]
Changed the following things: 
 * dots (lots of them) :)
 * summary (copied from debians descriptions of the package) 

Can you add the max length of `<summery>` in the documentation?
It also would be helpful if the validation would specify which `<li>` is too long and which to short. Line numbers would be great.

> The most important bit is the type value in id -- that has to be desktop in your case.
Just desktop? I thought it has to be the name of the desktop file. Just as the example on the doc page:

    <id>gnome-power-statistics.desktop</id>

From my system:

       $ locate .desktop | grep mars                                                                                             
          /usr/share/applications/mars.desktop

>      Not enough <p> content before <ul>

That means the "Game types" line, doesn't it?

**Comment by hughsie** [comment]
I've made the validator spit out the strings it's referring to; can you upload the file you've got now somewhere and I'll run the new validator on it please. Thanks.

**Comment by lightonflux** [comment]
It a web form for the validator planned?

**Comment by hughsie** [comment]
It actually works now, although I need to update my server to F21 before I can run the new appstream-glib version locally.

**Comment by lightonflux** [comment]
The web form doesn't work for me. I get an "connection failed" message in Firefox.

**Comment by lightonflux** [comment]
So i got an answer regarding the license and the text snippets from the site.

So we can use them and the email address works. 

I tried to use the form on the website again, but it doesn't work as of 20.02.2015. 

[file contents](https://gist.github.com/lightonflux/8ff4d569775c1afaa4a1)

**Comment by eXpl0it3r** [comment]
I've used the one provided and in active use by https://github.com/jwrdegoede/M.A.R.S./commit/4fb920e97d350a8777e06ce28c1657ad3a3fa3fb
