### ISSUE TITLE
compiling marsshooter on Fedora 23 fails

### ISSUE THREAD

**Issue by martinkg** [thelaui/M.A.R.S.#15]
The compilation of marsshooter-0.7.5-6.20140507gitc855d04 fails on Fedora 23.
The full build log is available here: 
https://kojipkgs.fedoraproject.org//work/tasks/3377/9073377/build.log

If you need further information, please let me know.

**Comment by xdevelnet-inc** [comment]
>https://kojipkgs.fedoraproject.org//work/tasks/3377/9073377/build.log
Not Found
The requested URL /work/tasks/3377/9073377/build.log was not found on this server.

Seriously?

**Comment by martinkg** [comment]
Am Samstag, den 18.04.2015, 05:55 -0700 schrieb Igor Demchencko:
>         https://kojipkgs.fedoraproject.org//work/tasks/3377/9073377/build.log
>         Not Found
>         The requested URL /work/tasks/3377/9073377/build.log was not
>         found on this server.
>         
> 
> Seriously?

Sorry, but the builds are only stored for 30 days.
Here is a a new build log: 
http://koji.fedoraproject.org/koji/taskinfo?taskID=9507608

**Comment by xdevelnet-inc** [comment]
its ok, nvm, i just saw date and removed my message:
>martinkg commented on 28 Feb

**Comment by carstene1ns** [comment]
Does it build on your local system (i.e. without the buildroot specific CFLAGS and such)?

**Comment by martinkg** [comment]
marsshooter builds fine on Fedora 21 + Fedora 22 but on Fedora 23 (rawhid) it fails.

i tried to build marsshooter for rawhide (fc23) on my local machine with the following command:
% mock -r fedora-rawhide-x86_64 --resultdir=/tmp/mock --rebuild ~/rpmbuild/SRPMS/marsshooter-0.7.5-6.20140507gitc855d04.fc21.src.rpm

The command to compile ms was:

cmake
make -j2

instead of:

%cmake -DCMAKE_CXX_FLAGS="%optflags" \
              -DCMAKE_VERBOSE_MAKEFILE=TRUE
make %{?_smp_mflags}

but the build fails with the identical error message:
M.A.R.S.-c855d044094a1d92317e38935d81ba938946132e/src/Menu/TutorialWindow.cpp:46: undefined reference to `sf::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::locale const&)'
CMakeFiles/mars.dir/Menu/OptionsMenu.cpp.o: In function `OptionsMenu::checkWidgets()':
/builddir/build/BUILD/M.A.R.S.-c855d044094a1d92317e38935d81ba938946132e/src/Menu/OptionsMenu.cpp:195: undefined reference to `sf::String::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >[abi:cxx11]() const'

**Comment by carstene1ns** [comment]
Well, if you use mock it will apply some additional flags as well. I meant to just do a traditional `git clone, cmake, make` run.
This way we will know, if the linker problems come from additional flags (for example `--as-needed` can cause problems when linking with wrong library order) or from a broken sfml package or such.

**Comment by martinkg** [comment]
problem now solved on Fedora 23 by using a newer gcc.
