### ISSUE TITLE
Clarify music license

### ISSUE THREAD

**Issue by Kasijjuf** [thelaui/M.A.R.S.#27]
How are Obsidian Shell licensing their music to M.A.R.S.? Is it via the CC-BY-SA license? Please also provide a link to an official statement by Obsidian Shell stating how they are licensing their music to M.A.R.S..

**Comment by Kasijjuf** [comment]
It appears this has been addressed downstream in the fork by @jwrdegoede.

See commit https://github.com/jwrdegoede/M.A.R.S./commit/985c26889f5397db90be84f4bb8316e6ceafa75e

**Comment by gunchleoc** [comment]
Unfortunately, the creators of this game have disappeared, so that fork is sort of the unofficial official version now.

**Comment by Kasijjuf** [comment]
Yeah, that's about I had concluded.

**Comment by eXpl0it3r** [comment]
I've cherry-picked https://github.com/jwrdegoede/M.A.R.S./commit/985c26889f5397db90be84f4bb8316e6ceafa75e into 3bf069f0e1348592b5cdf52deb45422376d16329

And will add the two ToDo's to the board
