### ISSUE TITLE
Retrieval of the history from the previous svn repository at source-forge.

### ISSUE THREAD

**Issue by SylvainBoilard** [thelaui/M.A.R.S.#3]
Hi,

It should be possible to retrieve the history from the svn repo at source-forge using git-svn.

You will need to clone from svn with git-svn in a different local repo, then pull from this local repo inside the M.A.R.S. repo using the --rebase option.

This option would also be needed to pull the requests based on the current head of the master branch, because it will have a different signature once the old repo will have been pulled.

Bye,
## 

Sylvain

**Comment by eXpl0it3r** [comment]
Done!

I didn't do any fancy additional work that one could do (like author extraction etc), but having the history at least seems like a good idea.
