### ISSUE TITLE
Man page for M.A.R.S

### ISSUE THREAD

**Issue by apoleon** [thelaui/M.A.R.S.#7]
Hi,

I'm working on an official Debian release for M.A.R.S. and would like to forward some patches to you.

This patch adds a man page for M.A.R.S.

https://gist.github.com/apoleon/8c3ab6997628bf975ffe

**Comment by eXpl0it3r** [comment]
Merged with 9f29edc40fa46b185b00b13a08e9bf31eccf5620 via https://github.com/jwrdegoede/M.A.R.S.
