### ISSUE TITLE
CMakeList.txt: installation of missing mars file fails

### ISSUE THREAD

**Issue by apoleon** [thelaui/M.A.R.S.#9]
The game tries to install the file resources/mars to /usr/share/menu. Unfortunately the file isn't present so the installation step fails.

I have written a new menu file for Debian and commented out the relevant part in CMakelist.txt

https://gist.github.com/apoleon/a8ee6ba29e8071db617c

**Comment by eXpl0it3r** [comment]
Implemented with f5519b9dde55727296737db071cb7d01c58b7bfa via https://github.com/jwrdegoede/M.A.R.S.
